// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4MQjmJGY8_zDgwO5v8juw9zuV4f_OIoE',
    appId: '1:726031470354:web:3e5e9483c786615e54adcb',
    messagingSenderId: '726031470354',
    projectId: 'watch-app-4b4c1',
    authDomain: 'watch-app-4b4c1.firebaseapp.com',
    databaseURL: 'https://watch-app-4b4c1-default-rtdb.firebaseio.com',
    storageBucket: 'watch-app-4b4c1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_Ag2IZwkM8lj5_vtW0oJUu6SrSDNhW5k',
    appId: '1:726031470354:android:ac651e260313850a54adcb',
    messagingSenderId: '726031470354',
    projectId: 'watch-app-4b4c1',
    databaseURL: 'https://watch-app-4b4c1-default-rtdb.firebaseio.com',
    storageBucket: 'watch-app-4b4c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyPt_Ee9KDWKgFRuiokDA4NTUQkOEzp7c',
    appId: '1:726031470354:ios:3baeb0b22e56a2ae54adcb',
    messagingSenderId: '726031470354',
    projectId: 'watch-app-4b4c1',
    databaseURL: 'https://watch-app-4b4c1-default-rtdb.firebaseio.com',
    storageBucket: 'watch-app-4b4c1.appspot.com',
    iosBundleId: 'com.example.watchApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyPt_Ee9KDWKgFRuiokDA4NTUQkOEzp7c',
    appId: '1:726031470354:ios:3baeb0b22e56a2ae54adcb',
    messagingSenderId: '726031470354',
    projectId: 'watch-app-4b4c1',
    databaseURL: 'https://watch-app-4b4c1-default-rtdb.firebaseio.com',
    storageBucket: 'watch-app-4b4c1.appspot.com',
    iosBundleId: 'com.example.watchApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4MQjmJGY8_zDgwO5v8juw9zuV4f_OIoE',
    appId: '1:726031470354:web:6995dfefc3a3461354adcb',
    messagingSenderId: '726031470354',
    projectId: 'watch-app-4b4c1',
    authDomain: 'watch-app-4b4c1.firebaseapp.com',
    databaseURL: 'https://watch-app-4b4c1-default-rtdb.firebaseio.com',
    storageBucket: 'watch-app-4b4c1.appspot.com',
  );
}
